/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AppworkspaceRouteRouteImport } from './routes/_app/(workspace)/route'
import { Route as AppworkspaceIndexRouteImport } from './routes/_app/(workspace)/index'
import { Route as publicApprovalLinkTokenRouteImport } from './routes/(public)/approval-link/$token'
import { Route as AppworkspaceSettingsIndexRouteImport } from './routes/_app/(workspace)/settings/index'
import { Route as AppworkspaceRuntimeIndexRouteImport } from './routes/_app/(workspace)/runtime/index'
import { Route as AppworkspacePluginsIndexRouteImport } from './routes/_app/(workspace)/plugins/index'
import { Route as AppworkspaceModelsIndexRouteImport } from './routes/_app/(workspace)/models/index'
import { Route as AppworkspaceEventsIndexRouteImport } from './routes/_app/(workspace)/events/index'
import { Route as AppworkspaceApprovalsIndexRouteImport } from './routes/_app/(workspace)/approvals/index'
import { Route as AppworkspacePluginsPluginIdRouteImport } from './routes/_app/(workspace)/plugins/$pluginId'
import { Route as AppworkspaceEventsEventIdRouteImport } from './routes/_app/(workspace)/events/$eventId'
import { Route as AppworkspaceApprovalsApprovalIdRouteImport } from './routes/_app/(workspace)/approvals/$approvalId'
import { Route as AppworkspaceRuntimeToolsInvocationIdRouteImport } from './routes/_app/(workspace)/runtime/tools/$invocationId'
import { Route as AppworkspaceRuntimeAgentsRunIdRouteImport } from './routes/_app/(workspace)/runtime/agents/$runId'
import { Route as AppworkspaceEventsEventIdAuditRouteImport } from './routes/_app/(workspace)/events/$eventId/audit'

const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceRouteRoute = AppworkspaceRouteRouteImport.update({
  id: '/_app/(workspace)',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceIndexRoute = AppworkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const publicApprovalLinkTokenRoute = publicApprovalLinkTokenRouteImport.update({
  id: '/(public)/approval-link/$token',
  path: '/approval-link/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceSettingsIndexRoute =
  AppworkspaceSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceRuntimeIndexRoute =
  AppworkspaceRuntimeIndexRouteImport.update({
    id: '/runtime/',
    path: '/runtime/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspacePluginsIndexRoute =
  AppworkspacePluginsIndexRouteImport.update({
    id: '/plugins/',
    path: '/plugins/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceModelsIndexRoute = AppworkspaceModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceEventsIndexRoute = AppworkspaceEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceApprovalsIndexRoute =
  AppworkspaceApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspacePluginsPluginIdRoute =
  AppworkspacePluginsPluginIdRouteImport.update({
    id: '/plugins/$pluginId',
    path: '/plugins/$pluginId',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceEventsEventIdRoute =
  AppworkspaceEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceApprovalsApprovalIdRoute =
  AppworkspaceApprovalsApprovalIdRouteImport.update({
    id: '/approvals/$approvalId',
    path: '/approvals/$approvalId',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceRuntimeToolsInvocationIdRoute =
  AppworkspaceRuntimeToolsInvocationIdRouteImport.update({
    id: '/runtime/tools/$invocationId',
    path: '/runtime/tools/$invocationId',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceRuntimeAgentsRunIdRoute =
  AppworkspaceRuntimeAgentsRunIdRouteImport.update({
    id: '/runtime/agents/$runId',
    path: '/runtime/agents/$runId',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceEventsEventIdAuditRoute =
  AppworkspaceEventsEventIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AppworkspaceEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/approval-link/$token': typeof publicApprovalLinkTokenRoute
  '/': typeof AppworkspaceIndexRoute
  '/approvals/$approvalId': typeof AppworkspaceApprovalsApprovalIdRoute
  '/events/$eventId': typeof AppworkspaceEventsEventIdRouteWithChildren
  '/plugins/$pluginId': typeof AppworkspacePluginsPluginIdRoute
  '/approvals/': typeof AppworkspaceApprovalsIndexRoute
  '/events/': typeof AppworkspaceEventsIndexRoute
  '/models/': typeof AppworkspaceModelsIndexRoute
  '/plugins/': typeof AppworkspacePluginsIndexRoute
  '/runtime/': typeof AppworkspaceRuntimeIndexRoute
  '/settings/': typeof AppworkspaceSettingsIndexRoute
  '/events/$eventId/audit': typeof AppworkspaceEventsEventIdAuditRoute
  '/runtime/agents/$runId': typeof AppworkspaceRuntimeAgentsRunIdRoute
  '/runtime/tools/$invocationId': typeof AppworkspaceRuntimeToolsInvocationIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/approval-link/$token': typeof publicApprovalLinkTokenRoute
  '/': typeof AppworkspaceIndexRoute
  '/approvals/$approvalId': typeof AppworkspaceApprovalsApprovalIdRoute
  '/events/$eventId': typeof AppworkspaceEventsEventIdRouteWithChildren
  '/plugins/$pluginId': typeof AppworkspacePluginsPluginIdRoute
  '/approvals': typeof AppworkspaceApprovalsIndexRoute
  '/events': typeof AppworkspaceEventsIndexRoute
  '/models': typeof AppworkspaceModelsIndexRoute
  '/plugins': typeof AppworkspacePluginsIndexRoute
  '/runtime': typeof AppworkspaceRuntimeIndexRoute
  '/settings': typeof AppworkspaceSettingsIndexRoute
  '/events/$eventId/audit': typeof AppworkspaceEventsEventIdAuditRoute
  '/runtime/agents/$runId': typeof AppworkspaceRuntimeAgentsRunIdRoute
  '/runtime/tools/$invocationId': typeof AppworkspaceRuntimeToolsInvocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/(workspace)': typeof AppworkspaceRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/approval-link/$token': typeof publicApprovalLinkTokenRoute
  '/_app/(workspace)/': typeof AppworkspaceIndexRoute
  '/_app/(workspace)/approvals/$approvalId': typeof AppworkspaceApprovalsApprovalIdRoute
  '/_app/(workspace)/events/$eventId': typeof AppworkspaceEventsEventIdRouteWithChildren
  '/_app/(workspace)/plugins/$pluginId': typeof AppworkspacePluginsPluginIdRoute
  '/_app/(workspace)/approvals/': typeof AppworkspaceApprovalsIndexRoute
  '/_app/(workspace)/events/': typeof AppworkspaceEventsIndexRoute
  '/_app/(workspace)/models/': typeof AppworkspaceModelsIndexRoute
  '/_app/(workspace)/plugins/': typeof AppworkspacePluginsIndexRoute
  '/_app/(workspace)/runtime/': typeof AppworkspaceRuntimeIndexRoute
  '/_app/(workspace)/settings/': typeof AppworkspaceSettingsIndexRoute
  '/_app/(workspace)/events/$eventId/audit': typeof AppworkspaceEventsEventIdAuditRoute
  '/_app/(workspace)/runtime/agents/$runId': typeof AppworkspaceRuntimeAgentsRunIdRoute
  '/_app/(workspace)/runtime/tools/$invocationId': typeof AppworkspaceRuntimeToolsInvocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/approval-link/$token'
    | '/'
    | '/approvals/$approvalId'
    | '/events/$eventId'
    | '/plugins/$pluginId'
    | '/approvals/'
    | '/events/'
    | '/models/'
    | '/plugins/'
    | '/runtime/'
    | '/settings/'
    | '/events/$eventId/audit'
    | '/runtime/agents/$runId'
    | '/runtime/tools/$invocationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approval-link/$token'
    | '/'
    | '/approvals/$approvalId'
    | '/events/$eventId'
    | '/plugins/$pluginId'
    | '/approvals'
    | '/events'
    | '/models'
    | '/plugins'
    | '/runtime'
    | '/settings'
    | '/events/$eventId/audit'
    | '/runtime/agents/$runId'
    | '/runtime/tools/$invocationId'
  id:
    | '__root__'
    | '/_app/(workspace)'
    | '/(public)/login'
    | '/(public)/approval-link/$token'
    | '/_app/(workspace)/'
    | '/_app/(workspace)/approvals/$approvalId'
    | '/_app/(workspace)/events/$eventId'
    | '/_app/(workspace)/plugins/$pluginId'
    | '/_app/(workspace)/approvals/'
    | '/_app/(workspace)/events/'
    | '/_app/(workspace)/models/'
    | '/_app/(workspace)/plugins/'
    | '/_app/(workspace)/runtime/'
    | '/_app/(workspace)/settings/'
    | '/_app/(workspace)/events/$eventId/audit'
    | '/_app/(workspace)/runtime/agents/$runId'
    | '/_app/(workspace)/runtime/tools/$invocationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppworkspaceRouteRoute: typeof AppworkspaceRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicApprovalLinkTokenRoute: typeof publicApprovalLinkTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)': {
      id: '/_app/(workspace)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppworkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)/': {
      id: '/_app/(workspace)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppworkspaceIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/(public)/approval-link/$token': {
      id: '/(public)/approval-link/$token'
      path: '/approval-link/$token'
      fullPath: '/approval-link/$token'
      preLoaderRoute: typeof publicApprovalLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)/settings/': {
      id: '/_app/(workspace)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppworkspaceSettingsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/runtime/': {
      id: '/_app/(workspace)/runtime/'
      path: '/runtime'
      fullPath: '/runtime/'
      preLoaderRoute: typeof AppworkspaceRuntimeIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/plugins/': {
      id: '/_app/(workspace)/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AppworkspacePluginsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/models/': {
      id: '/_app/(workspace)/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AppworkspaceModelsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/events/': {
      id: '/_app/(workspace)/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppworkspaceEventsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/approvals/': {
      id: '/_app/(workspace)/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AppworkspaceApprovalsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/plugins/$pluginId': {
      id: '/_app/(workspace)/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof AppworkspacePluginsPluginIdRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/events/$eventId': {
      id: '/_app/(workspace)/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppworkspaceEventsEventIdRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/approvals/$approvalId': {
      id: '/_app/(workspace)/approvals/$approvalId'
      path: '/approvals/$approvalId'
      fullPath: '/approvals/$approvalId'
      preLoaderRoute: typeof AppworkspaceApprovalsApprovalIdRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/runtime/tools/$invocationId': {
      id: '/_app/(workspace)/runtime/tools/$invocationId'
      path: '/runtime/tools/$invocationId'
      fullPath: '/runtime/tools/$invocationId'
      preLoaderRoute: typeof AppworkspaceRuntimeToolsInvocationIdRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/runtime/agents/$runId': {
      id: '/_app/(workspace)/runtime/agents/$runId'
      path: '/runtime/agents/$runId'
      fullPath: '/runtime/agents/$runId'
      preLoaderRoute: typeof AppworkspaceRuntimeAgentsRunIdRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/events/$eventId/audit': {
      id: '/_app/(workspace)/events/$eventId/audit'
      path: '/audit'
      fullPath: '/events/$eventId/audit'
      preLoaderRoute: typeof AppworkspaceEventsEventIdAuditRouteImport
      parentRoute: typeof AppworkspaceEventsEventIdRoute
    }
  }
}

interface AppworkspaceEventsEventIdRouteChildren {
  AppworkspaceEventsEventIdAuditRoute: typeof AppworkspaceEventsEventIdAuditRoute
}

const AppworkspaceEventsEventIdRouteChildren: AppworkspaceEventsEventIdRouteChildren =
  {
    AppworkspaceEventsEventIdAuditRoute: AppworkspaceEventsEventIdAuditRoute,
  }

const AppworkspaceEventsEventIdRouteWithChildren =
  AppworkspaceEventsEventIdRoute._addFileChildren(
    AppworkspaceEventsEventIdRouteChildren,
  )

interface AppworkspaceRouteRouteChildren {
  AppworkspaceIndexRoute: typeof AppworkspaceIndexRoute
  AppworkspaceApprovalsApprovalIdRoute: typeof AppworkspaceApprovalsApprovalIdRoute
  AppworkspaceEventsEventIdRoute: typeof AppworkspaceEventsEventIdRouteWithChildren
  AppworkspacePluginsPluginIdRoute: typeof AppworkspacePluginsPluginIdRoute
  AppworkspaceApprovalsIndexRoute: typeof AppworkspaceApprovalsIndexRoute
  AppworkspaceEventsIndexRoute: typeof AppworkspaceEventsIndexRoute
  AppworkspaceModelsIndexRoute: typeof AppworkspaceModelsIndexRoute
  AppworkspacePluginsIndexRoute: typeof AppworkspacePluginsIndexRoute
  AppworkspaceRuntimeIndexRoute: typeof AppworkspaceRuntimeIndexRoute
  AppworkspaceSettingsIndexRoute: typeof AppworkspaceSettingsIndexRoute
  AppworkspaceRuntimeAgentsRunIdRoute: typeof AppworkspaceRuntimeAgentsRunIdRoute
  AppworkspaceRuntimeToolsInvocationIdRoute: typeof AppworkspaceRuntimeToolsInvocationIdRoute
}

const AppworkspaceRouteRouteChildren: AppworkspaceRouteRouteChildren = {
  AppworkspaceIndexRoute: AppworkspaceIndexRoute,
  AppworkspaceApprovalsApprovalIdRoute: AppworkspaceApprovalsApprovalIdRoute,
  AppworkspaceEventsEventIdRoute: AppworkspaceEventsEventIdRouteWithChildren,
  AppworkspacePluginsPluginIdRoute: AppworkspacePluginsPluginIdRoute,
  AppworkspaceApprovalsIndexRoute: AppworkspaceApprovalsIndexRoute,
  AppworkspaceEventsIndexRoute: AppworkspaceEventsIndexRoute,
  AppworkspaceModelsIndexRoute: AppworkspaceModelsIndexRoute,
  AppworkspacePluginsIndexRoute: AppworkspacePluginsIndexRoute,
  AppworkspaceRuntimeIndexRoute: AppworkspaceRuntimeIndexRoute,
  AppworkspaceSettingsIndexRoute: AppworkspaceSettingsIndexRoute,
  AppworkspaceRuntimeAgentsRunIdRoute: AppworkspaceRuntimeAgentsRunIdRoute,
  AppworkspaceRuntimeToolsInvocationIdRoute:
    AppworkspaceRuntimeToolsInvocationIdRoute,
}

const AppworkspaceRouteRouteWithChildren =
  AppworkspaceRouteRoute._addFileChildren(AppworkspaceRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppworkspaceRouteRoute: AppworkspaceRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicApprovalLinkTokenRoute: publicApprovalLinkTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
