/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AppworkspaceRouteRouteImport } from './routes/_app/(workspace)/route'
import { Route as AppworkspaceIndexRouteImport } from './routes/_app/(workspace)/index'
import { Route as publicApprovalLinkTokenRouteImport } from './routes/(public)/approval-link/$token'
import { Route as AppworkspaceToolsIndexRouteImport } from './routes/_app/(workspace)/tools/index'
import { Route as AppworkspaceSkillsIndexRouteImport } from './routes/_app/(workspace)/skills/index'
import { Route as AppworkspaceSettingsIndexRouteImport } from './routes/_app/(workspace)/settings/index'
import { Route as AppworkspaceRuntimeIndexRouteImport } from './routes/_app/(workspace)/runtime/index'
import { Route as AppworkspacePluginsIndexRouteImport } from './routes/_app/(workspace)/plugins/index'
import { Route as AppworkspaceIndustriesIndexRouteImport } from './routes/_app/(workspace)/industries/index'
import { Route as AppworkspaceEventsIndexRouteImport } from './routes/_app/(workspace)/events/index'
import { Route as AppworkspaceApprovalsIndexRouteImport } from './routes/_app/(workspace)/approvals/index'
import { Route as AppworkspaceEventsEventIdRouteImport } from './routes/_app/(workspace)/events/$eventId'
import { Route as AppworkspaceApprovalsApprovalIdRouteImport } from './routes/_app/(workspace)/approvals/$approvalId'
import { Route as AppworkspaceEventsEventIdAuditRouteImport } from './routes/_app/(workspace)/events/$eventId/audit'

const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceRouteRoute = AppworkspaceRouteRouteImport.update({
  id: '/_app/(workspace)',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceIndexRoute = AppworkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const publicApprovalLinkTokenRoute = publicApprovalLinkTokenRouteImport.update({
  id: '/(public)/approval-link/$token',
  path: '/approval-link/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceToolsIndexRoute = AppworkspaceToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceSkillsIndexRoute = AppworkspaceSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceSettingsIndexRoute =
  AppworkspaceSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceRuntimeIndexRoute =
  AppworkspaceRuntimeIndexRouteImport.update({
    id: '/runtime/',
    path: '/runtime/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspacePluginsIndexRoute =
  AppworkspacePluginsIndexRouteImport.update({
    id: '/plugins/',
    path: '/plugins/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceIndustriesIndexRoute =
  AppworkspaceIndustriesIndexRouteImport.update({
    id: '/industries/',
    path: '/industries/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceEventsIndexRoute = AppworkspaceEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceApprovalsIndexRoute =
  AppworkspaceApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceEventsEventIdRoute =
  AppworkspaceEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceApprovalsApprovalIdRoute =
  AppworkspaceApprovalsApprovalIdRouteImport.update({
    id: '/approvals/$approvalId',
    path: '/approvals/$approvalId',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceEventsEventIdAuditRoute =
  AppworkspaceEventsEventIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AppworkspaceEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/approval-link/$token': typeof publicApprovalLinkTokenRoute
  '/': typeof AppworkspaceIndexRoute
  '/approvals/$approvalId': typeof AppworkspaceApprovalsApprovalIdRoute
  '/events/$eventId': typeof AppworkspaceEventsEventIdRouteWithChildren
  '/approvals/': typeof AppworkspaceApprovalsIndexRoute
  '/events/': typeof AppworkspaceEventsIndexRoute
  '/industries/': typeof AppworkspaceIndustriesIndexRoute
  '/plugins/': typeof AppworkspacePluginsIndexRoute
  '/runtime/': typeof AppworkspaceRuntimeIndexRoute
  '/settings/': typeof AppworkspaceSettingsIndexRoute
  '/skills/': typeof AppworkspaceSkillsIndexRoute
  '/tools/': typeof AppworkspaceToolsIndexRoute
  '/events/$eventId/audit': typeof AppworkspaceEventsEventIdAuditRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/approval-link/$token': typeof publicApprovalLinkTokenRoute
  '/': typeof AppworkspaceIndexRoute
  '/approvals/$approvalId': typeof AppworkspaceApprovalsApprovalIdRoute
  '/events/$eventId': typeof AppworkspaceEventsEventIdRouteWithChildren
  '/approvals': typeof AppworkspaceApprovalsIndexRoute
  '/events': typeof AppworkspaceEventsIndexRoute
  '/industries': typeof AppworkspaceIndustriesIndexRoute
  '/plugins': typeof AppworkspacePluginsIndexRoute
  '/runtime': typeof AppworkspaceRuntimeIndexRoute
  '/settings': typeof AppworkspaceSettingsIndexRoute
  '/skills': typeof AppworkspaceSkillsIndexRoute
  '/tools': typeof AppworkspaceToolsIndexRoute
  '/events/$eventId/audit': typeof AppworkspaceEventsEventIdAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/(workspace)': typeof AppworkspaceRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/approval-link/$token': typeof publicApprovalLinkTokenRoute
  '/_app/(workspace)/': typeof AppworkspaceIndexRoute
  '/_app/(workspace)/approvals/$approvalId': typeof AppworkspaceApprovalsApprovalIdRoute
  '/_app/(workspace)/events/$eventId': typeof AppworkspaceEventsEventIdRouteWithChildren
  '/_app/(workspace)/approvals/': typeof AppworkspaceApprovalsIndexRoute
  '/_app/(workspace)/events/': typeof AppworkspaceEventsIndexRoute
  '/_app/(workspace)/industries/': typeof AppworkspaceIndustriesIndexRoute
  '/_app/(workspace)/plugins/': typeof AppworkspacePluginsIndexRoute
  '/_app/(workspace)/runtime/': typeof AppworkspaceRuntimeIndexRoute
  '/_app/(workspace)/settings/': typeof AppworkspaceSettingsIndexRoute
  '/_app/(workspace)/skills/': typeof AppworkspaceSkillsIndexRoute
  '/_app/(workspace)/tools/': typeof AppworkspaceToolsIndexRoute
  '/_app/(workspace)/events/$eventId/audit': typeof AppworkspaceEventsEventIdAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/approval-link/$token'
    | '/'
    | '/approvals/$approvalId'
    | '/events/$eventId'
    | '/approvals/'
    | '/events/'
    | '/industries/'
    | '/plugins/'
    | '/runtime/'
    | '/settings/'
    | '/skills/'
    | '/tools/'
    | '/events/$eventId/audit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approval-link/$token'
    | '/'
    | '/approvals/$approvalId'
    | '/events/$eventId'
    | '/approvals'
    | '/events'
    | '/industries'
    | '/plugins'
    | '/runtime'
    | '/settings'
    | '/skills'
    | '/tools'
    | '/events/$eventId/audit'
  id:
    | '__root__'
    | '/_app/(workspace)'
    | '/(public)/login'
    | '/(public)/approval-link/$token'
    | '/_app/(workspace)/'
    | '/_app/(workspace)/approvals/$approvalId'
    | '/_app/(workspace)/events/$eventId'
    | '/_app/(workspace)/approvals/'
    | '/_app/(workspace)/events/'
    | '/_app/(workspace)/industries/'
    | '/_app/(workspace)/plugins/'
    | '/_app/(workspace)/runtime/'
    | '/_app/(workspace)/settings/'
    | '/_app/(workspace)/skills/'
    | '/_app/(workspace)/tools/'
    | '/_app/(workspace)/events/$eventId/audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppworkspaceRouteRoute: typeof AppworkspaceRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicApprovalLinkTokenRoute: typeof publicApprovalLinkTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)': {
      id: '/_app/(workspace)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppworkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)/': {
      id: '/_app/(workspace)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppworkspaceIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/(public)/approval-link/$token': {
      id: '/(public)/approval-link/$token'
      path: '/approval-link/$token'
      fullPath: '/approval-link/$token'
      preLoaderRoute: typeof publicApprovalLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)/tools/': {
      id: '/_app/(workspace)/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppworkspaceToolsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/skills/': {
      id: '/_app/(workspace)/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AppworkspaceSkillsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/settings/': {
      id: '/_app/(workspace)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppworkspaceSettingsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/runtime/': {
      id: '/_app/(workspace)/runtime/'
      path: '/runtime'
      fullPath: '/runtime/'
      preLoaderRoute: typeof AppworkspaceRuntimeIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/plugins/': {
      id: '/_app/(workspace)/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AppworkspacePluginsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/industries/': {
      id: '/_app/(workspace)/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof AppworkspaceIndustriesIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/events/': {
      id: '/_app/(workspace)/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppworkspaceEventsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/approvals/': {
      id: '/_app/(workspace)/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AppworkspaceApprovalsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/events/$eventId': {
      id: '/_app/(workspace)/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppworkspaceEventsEventIdRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/approvals/$approvalId': {
      id: '/_app/(workspace)/approvals/$approvalId'
      path: '/approvals/$approvalId'
      fullPath: '/approvals/$approvalId'
      preLoaderRoute: typeof AppworkspaceApprovalsApprovalIdRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/events/$eventId/audit': {
      id: '/_app/(workspace)/events/$eventId/audit'
      path: '/audit'
      fullPath: '/events/$eventId/audit'
      preLoaderRoute: typeof AppworkspaceEventsEventIdAuditRouteImport
      parentRoute: typeof AppworkspaceEventsEventIdRoute
    }
  }
}

interface AppworkspaceEventsEventIdRouteChildren {
  AppworkspaceEventsEventIdAuditRoute: typeof AppworkspaceEventsEventIdAuditRoute
}

const AppworkspaceEventsEventIdRouteChildren: AppworkspaceEventsEventIdRouteChildren =
  {
    AppworkspaceEventsEventIdAuditRoute: AppworkspaceEventsEventIdAuditRoute,
  }

const AppworkspaceEventsEventIdRouteWithChildren =
  AppworkspaceEventsEventIdRoute._addFileChildren(
    AppworkspaceEventsEventIdRouteChildren,
  )

interface AppworkspaceRouteRouteChildren {
  AppworkspaceIndexRoute: typeof AppworkspaceIndexRoute
  AppworkspaceApprovalsApprovalIdRoute: typeof AppworkspaceApprovalsApprovalIdRoute
  AppworkspaceEventsEventIdRoute: typeof AppworkspaceEventsEventIdRouteWithChildren
  AppworkspaceApprovalsIndexRoute: typeof AppworkspaceApprovalsIndexRoute
  AppworkspaceEventsIndexRoute: typeof AppworkspaceEventsIndexRoute
  AppworkspaceIndustriesIndexRoute: typeof AppworkspaceIndustriesIndexRoute
  AppworkspacePluginsIndexRoute: typeof AppworkspacePluginsIndexRoute
  AppworkspaceRuntimeIndexRoute: typeof AppworkspaceRuntimeIndexRoute
  AppworkspaceSettingsIndexRoute: typeof AppworkspaceSettingsIndexRoute
  AppworkspaceSkillsIndexRoute: typeof AppworkspaceSkillsIndexRoute
  AppworkspaceToolsIndexRoute: typeof AppworkspaceToolsIndexRoute
}

const AppworkspaceRouteRouteChildren: AppworkspaceRouteRouteChildren = {
  AppworkspaceIndexRoute: AppworkspaceIndexRoute,
  AppworkspaceApprovalsApprovalIdRoute: AppworkspaceApprovalsApprovalIdRoute,
  AppworkspaceEventsEventIdRoute: AppworkspaceEventsEventIdRouteWithChildren,
  AppworkspaceApprovalsIndexRoute: AppworkspaceApprovalsIndexRoute,
  AppworkspaceEventsIndexRoute: AppworkspaceEventsIndexRoute,
  AppworkspaceIndustriesIndexRoute: AppworkspaceIndustriesIndexRoute,
  AppworkspacePluginsIndexRoute: AppworkspacePluginsIndexRoute,
  AppworkspaceRuntimeIndexRoute: AppworkspaceRuntimeIndexRoute,
  AppworkspaceSettingsIndexRoute: AppworkspaceSettingsIndexRoute,
  AppworkspaceSkillsIndexRoute: AppworkspaceSkillsIndexRoute,
  AppworkspaceToolsIndexRoute: AppworkspaceToolsIndexRoute,
}

const AppworkspaceRouteRouteWithChildren =
  AppworkspaceRouteRoute._addFileChildren(AppworkspaceRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppworkspaceRouteRoute: AppworkspaceRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicApprovalLinkTokenRoute: publicApprovalLinkTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
