/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AppworkspaceRouteRouteImport } from './routes/_app/(workspace)/route'
import { Route as AppworkspaceToolsIndexRouteImport } from './routes/_app/(workspace)/tools/index'
import { Route as AppworkspaceSkillsIndexRouteImport } from './routes/_app/(workspace)/skills/index'
import { Route as AppworkspaceSettingsIndexRouteImport } from './routes/_app/(workspace)/settings/index'
import { Route as AppworkspaceRuntimeIndexRouteImport } from './routes/_app/(workspace)/runtime/index'
import { Route as AppworkspacePluginsIndexRouteImport } from './routes/_app/(workspace)/plugins/index'
import { Route as AppworkspaceIndustriesIndexRouteImport } from './routes/_app/(workspace)/industries/index'
import { Route as AppworkspaceEventsIndexRouteImport } from './routes/_app/(workspace)/events/index'
import { Route as AppworkspaceApprovalsIndexRouteImport } from './routes/_app/(workspace)/approvals/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceRouteRoute = AppworkspaceRouteRouteImport.update({
  id: '/_app/(workspace)',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const AppworkspaceToolsIndexRoute = AppworkspaceToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceSkillsIndexRoute = AppworkspaceSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceSettingsIndexRoute =
  AppworkspaceSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceRuntimeIndexRoute =
  AppworkspaceRuntimeIndexRouteImport.update({
    id: '/runtime/',
    path: '/runtime/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspacePluginsIndexRoute =
  AppworkspacePluginsIndexRouteImport.update({
    id: '/plugins/',
    path: '/plugins/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceIndustriesIndexRoute =
  AppworkspaceIndustriesIndexRouteImport.update({
    id: '/industries/',
    path: '/industries/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)
const AppworkspaceEventsIndexRoute = AppworkspaceEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppworkspaceRouteRoute,
} as any)
const AppworkspaceApprovalsIndexRoute =
  AppworkspaceApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AppworkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/approvals/': typeof AppworkspaceApprovalsIndexRoute
  '/events/': typeof AppworkspaceEventsIndexRoute
  '/industries/': typeof AppworkspaceIndustriesIndexRoute
  '/plugins/': typeof AppworkspacePluginsIndexRoute
  '/runtime/': typeof AppworkspaceRuntimeIndexRoute
  '/settings/': typeof AppworkspaceSettingsIndexRoute
  '/skills/': typeof AppworkspaceSkillsIndexRoute
  '/tools/': typeof AppworkspaceToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/approvals': typeof AppworkspaceApprovalsIndexRoute
  '/events': typeof AppworkspaceEventsIndexRoute
  '/industries': typeof AppworkspaceIndustriesIndexRoute
  '/plugins': typeof AppworkspacePluginsIndexRoute
  '/runtime': typeof AppworkspaceRuntimeIndexRoute
  '/settings': typeof AppworkspaceSettingsIndexRoute
  '/skills': typeof AppworkspaceSkillsIndexRoute
  '/tools': typeof AppworkspaceToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app/(workspace)': typeof AppworkspaceRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/_app/(workspace)/approvals/': typeof AppworkspaceApprovalsIndexRoute
  '/_app/(workspace)/events/': typeof AppworkspaceEventsIndexRoute
  '/_app/(workspace)/industries/': typeof AppworkspaceIndustriesIndexRoute
  '/_app/(workspace)/plugins/': typeof AppworkspacePluginsIndexRoute
  '/_app/(workspace)/runtime/': typeof AppworkspaceRuntimeIndexRoute
  '/_app/(workspace)/settings/': typeof AppworkspaceSettingsIndexRoute
  '/_app/(workspace)/skills/': typeof AppworkspaceSkillsIndexRoute
  '/_app/(workspace)/tools/': typeof AppworkspaceToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals/'
    | '/events/'
    | '/industries/'
    | '/plugins/'
    | '/runtime/'
    | '/settings/'
    | '/skills/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/approvals'
    | '/events'
    | '/industries'
    | '/plugins'
    | '/runtime'
    | '/settings'
    | '/skills'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/_app/(workspace)'
    | '/(public)/login'
    | '/_app/(workspace)/approvals/'
    | '/_app/(workspace)/events/'
    | '/_app/(workspace)/industries/'
    | '/_app/(workspace)/plugins/'
    | '/_app/(workspace)/runtime/'
    | '/_app/(workspace)/settings/'
    | '/_app/(workspace)/skills/'
    | '/_app/(workspace)/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppworkspaceRouteRoute: typeof AppworkspaceRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)': {
      id: '/_app/(workspace)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppworkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(workspace)/tools/': {
      id: '/_app/(workspace)/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppworkspaceToolsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/skills/': {
      id: '/_app/(workspace)/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AppworkspaceSkillsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/settings/': {
      id: '/_app/(workspace)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppworkspaceSettingsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/runtime/': {
      id: '/_app/(workspace)/runtime/'
      path: '/runtime'
      fullPath: '/runtime/'
      preLoaderRoute: typeof AppworkspaceRuntimeIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/plugins/': {
      id: '/_app/(workspace)/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AppworkspacePluginsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/industries/': {
      id: '/_app/(workspace)/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof AppworkspaceIndustriesIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/events/': {
      id: '/_app/(workspace)/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppworkspaceEventsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
    '/_app/(workspace)/approvals/': {
      id: '/_app/(workspace)/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AppworkspaceApprovalsIndexRouteImport
      parentRoute: typeof AppworkspaceRouteRoute
    }
  }
}

interface AppworkspaceRouteRouteChildren {
  AppworkspaceApprovalsIndexRoute: typeof AppworkspaceApprovalsIndexRoute
  AppworkspaceEventsIndexRoute: typeof AppworkspaceEventsIndexRoute
  AppworkspaceIndustriesIndexRoute: typeof AppworkspaceIndustriesIndexRoute
  AppworkspacePluginsIndexRoute: typeof AppworkspacePluginsIndexRoute
  AppworkspaceRuntimeIndexRoute: typeof AppworkspaceRuntimeIndexRoute
  AppworkspaceSettingsIndexRoute: typeof AppworkspaceSettingsIndexRoute
  AppworkspaceSkillsIndexRoute: typeof AppworkspaceSkillsIndexRoute
  AppworkspaceToolsIndexRoute: typeof AppworkspaceToolsIndexRoute
}

const AppworkspaceRouteRouteChildren: AppworkspaceRouteRouteChildren = {
  AppworkspaceApprovalsIndexRoute: AppworkspaceApprovalsIndexRoute,
  AppworkspaceEventsIndexRoute: AppworkspaceEventsIndexRoute,
  AppworkspaceIndustriesIndexRoute: AppworkspaceIndustriesIndexRoute,
  AppworkspacePluginsIndexRoute: AppworkspacePluginsIndexRoute,
  AppworkspaceRuntimeIndexRoute: AppworkspaceRuntimeIndexRoute,
  AppworkspaceSettingsIndexRoute: AppworkspaceSettingsIndexRoute,
  AppworkspaceSkillsIndexRoute: AppworkspaceSkillsIndexRoute,
  AppworkspaceToolsIndexRoute: AppworkspaceToolsIndexRoute,
}

const AppworkspaceRouteRouteWithChildren =
  AppworkspaceRouteRoute._addFileChildren(AppworkspaceRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppworkspaceRouteRoute: AppworkspaceRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
