from __future__ import annotations

from quantagent.plugin_sdk import BasePlugin, PluginInvokeResult, SourceFetchResult, SourceItemDraft


class PlaceholderSourcePlugin(BasePlugin):
    async def invoke(self, request):
        query = request.input.get("query") or self.context.config.get("query") or "placeholder"
        # Demo plugin only returns the source DTO; platform services own persistence and routing.
        output = SourceFetchResult(
            items=(
                SourceItemDraft(
                    external_id=f"placeholder:{query}",
                    title=f"Placeholder item for {query}",
                    content="Generated by the official placeholder source plugin.",
                    raw_payload={"query": query},
                    metadata={
                        "plugin_id": self.context.plugin_id,
                        "request_id": request.request_id,
                    },
                ),
            ),
            metadata={"source": "placeholder"},
        )
        return PluginInvokeResult(output=output.to_mapping())


plugin = PlaceholderSourcePlugin
